#include "stratagems.h"
// #include "quantum.h"

// region Orbital Attack
#define gatling_barrage SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127)
#define walking_barrage SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127)
#define he120mm_barrage SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127)
#define he380mm_barrage SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127)
#define gas_strike SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
#define ems_strike SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127)
#define osmoke_strike SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127)
#define airburst_strike SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
#define precision_strike SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127)
#define railcannon_strike SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
#define orbital_laser SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127)
// endregion

// region Eagle_Attack
#define strafing_run SS_DOWN(X_LCTL) SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
#define napalm_airstrike SS_DOWN(X_LCTL) SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127)
#define rocket_110mm SS_DOWN(X_LCTL) SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127)
#define air_strike SS_DOWN(X_LCTL) SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
#define smoke_strike SS_DOWN(X_LCTL) SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127)
#define cluster_bomb SS_DOWN(X_LCTL) SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
#define bomb_500k SS_DOWN(X_LCTL) SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127)
// endregion

// region Sentry Attack
#define machine_gun SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127)
#define gatling SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127)
#define autocannon SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127)
#define rocket  SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127)
#define mortar  SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127)
#define ems_mortar  SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
  // endregion

// region Send Support
#define resupply SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
#define sos_beacon SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127)
#define patriot_exosuit SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127)
#define supply_pack SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127)
#define jump_pack SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127)
#define ballistic_shield SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127)
#define shield_generator_pack SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
#define guard_dog SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127)
#define guard_rover SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
#define shield_generator SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
// endregion

//  region Weapon Support
#define grenade_launcher SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127)
#define expandable_antitank SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
#define recoiless_rifle SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127)
#define spear SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127)
#define railgun SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
#define antimaterial_rifle SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127)
#define wautocannon SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
#define laser_cannon SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127)
#define quasar_cannon SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
#define arc_thrower SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127)
#define flame_thrower SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127)
#define wmachine_gun SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_RIGHT) SS_DELAY(157) SS_UP(X_RIGHT) SS_DELAY(127)
#define stalwart SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127)
#define heavy_machinegun SS_DOWN(X_LCTL)  SS_DELAY(157) SS_UP(X_LCTL) SS_DELAY(427) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_LEFT) SS_DELAY(157) SS_UP(X_LEFT) SS_DELAY(127) SS_DOWN(X_UP) SS_DELAY(157) SS_UP(X_UP) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127) SS_DOWN(X_DOWN) SS_DELAY(157) SS_UP(X_DOWN) SS_DELAY(127)
// endregion

void orbital_attack(int attack) {
    switch (attack) {
        case 1:
            SEND_STRING(gatling_barrage);
            break;
        case 2:
            SEND_STRING(walking_barrage);
            break;
        case 3:
            SEND_STRING(he120mm_barrage);
            break;
        case 4:
            SEND_STRING(he380mm_barrage);
            break;
        case 5:
            SEND_STRING(gas_strike);
            break;
        case 6:
            SEND_STRING(ems_strike);
            break;
        case 7:
            SEND_STRING(smoke_strike);
            break;
        case 8:
            SEND_STRING(airburst_strike);
            break;
        case 9:
            SEND_STRING(precision_strike);
            break;
        case 10:
            SEND_STRING(railcannon_strike);
            break;
        case 11:
            SEND_STRING(orbital_laser);
            break;
    }
}

void eagle_attack(int attack) {
    switch (attack) {
        case 1:
            SEND_STRING(strafing_run);
            break;
        case 2:
            SEND_STRING(napalm_airstrike);
            break;
        case 3:
            SEND_STRING(rocket_110mm);
            break;
        case 4:
            SEND_STRING(air_strike);
            break;
        case 5:
            SEND_STRING(smoke_strike);
            break;
        case 6:
            SEND_STRING(cluster_bomb);
            break;
        case 7:
            SEND_STRING(bomb_500k);
            break;
    }
}

void sentry_attack(int attack) {
    switch (attack) {
        case 1:
            SEND_STRING(machine_gun);
            break;
        case 2:
            SEND_STRING(gatling);
            break;
        case 3:
            SEND_STRING(autocannon);
            break;
        case 4:
            SEND_STRING(rocket);
            break;
        case 5:
            SEND_STRING(mortar);
            break;
        case 6:
            SEND_STRING(ems_mortar);
            break;
    }
}

void send_support(int attack) {
    switch (attack) {
        case 1:
            SEND_STRING(resupply);
            break;
        case 2:
            SEND_STRING(sos_beacon);
            break;
        case 3:
            SEND_STRING(patriot_exosuit);
            break;
        case 4:
            SEND_STRING(supply_pack);
            break;
        case 5:
            SEND_STRING(jump_pack);
            break;
        case 6:
            SEND_STRING(ballistic_shield);
            break;
        case 7:
            SEND_STRING(shield_generator_pack);
            break;
        case 8:
            SEND_STRING(guard_dog);
            break;
        case 9:
            SEND_STRING(guard_rover);
            break;
        case 10:
            SEND_STRING(shield_generator);
            break;
    }
}

void weapon_support(int attack) {
    switch (attack) {
        case 1:
            SEND_STRING(grenade_launcher);
            break;
        case 2:
            SEND_STRING(expandable_antitank);
            break;
        case 3:
            SEND_STRING(recoiless_rifle);
            break;
        case 4:
            SEND_STRING(spear);
            break;
        case 5:
            SEND_STRING(railgun);
            break;
        case 6:
            SEND_STRING(antimaterial_rifle);
            break;
        case 7:
            SEND_STRING(wautocannon);
            break;
        case 8:
            SEND_STRING(laser_cannon);
            break;
        case 9:
            SEND_STRING(quasar_cannon);
            break;
        case 10:
            SEND_STRING(arc_thrower);
            break;
        case 11:
            SEND_STRING(flame_thrower);
            break;
        case 12:
            SEND_STRING(wmachine_gun);
            break;
        case 13:
            SEND_STRING(stalwart);
            break;
        case 14:
            SEND_STRING(heavy_machinegun);
            break;
    }
}
